In [1]:
from numpy import *

In [2]:
a = array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# shape : It is used find the dimensional shape of the array
print(a.shape)

(2, 4)


In [4]:
#ndim : returns an integer that tells us how many dimensions the array have.
print("ndim",a.ndim)

ndim 2


In [5]:
#size : return the size of the array
print("Size : ",a.size)

Size :  8


In [6]:
#dtype : return the datatype of the array
print("datatype : ",a.dtype)

datatype :  int32


In [7]:
#itemsize : The element size of this data-type object
print(a.itemsize)

4


In [8]:
#data : will print the data of the array intenally
print(a.data)

In [9]:
m1 = array([[1,2],[3,4]])
m2 = array([[5,6],[7,8]])

In [10]:
print(m1)
print(m2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [11]:
#dot : return the multiplication of the matrix
mul = dot(m1,m2)  
print(mul)

[[19 22]
 [43 50]]


In [12]:
#multiply : it only multiply the elements
mult = multiply(m1,m2) #only multiplication
print(mult)

[[ 5 12]
 [21 32]]


In [13]:
#subtract : will subtract the matrix
subtrac = subtract(m2,m1)
print(subtrac)

[[4 4]
 [4 4]]


In [14]:
#add : will add the two or more matrix
addM = add(m1,m2)
print(addM)

[[ 6  8]
 [10 12]]


In [23]:
#vstack : arrange the array vertically
v = vstack((m1,m2))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
#hstack : arrange the array horizontally
h = hstack((m1,m2))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
b = array([4,5,56,7,8,9,12,45])

#starting from the 2nd element to the end
print(b[2:])

#starting from first element to the 2-1 element
print(b[:2])

#starting from the 2nd element to the 4th element
print(b[2:5])

#in the 1st matrix of m1 2 elements
print(m1[1:2])

#sum of all the elements in the array
print(b.sum())


[56  7  8  9 12 45]
[4 5]
[56  7  8]
[[3 4]]
146


In [21]:
c = array([1,2,3,4,5,6,7,8,9])

#reshape : shape the array according to our choice
print(c.reshape(3,3))

#max = maximum element from the array 
print(c.max())

#min : minimum element from the array 
print(c.min())

re = c.reshape(3,3)
#axis=1 means row wise maximum
print("Max in row is : ",re.max(axis=1))

#axis=0 means column wise minimum  
print("Min in row is : ",re.min(axis=0))  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
Max in row is :  [3 6 9]
Min in row is :  [1 2 3]


In [20]:
m4 = array([4,9,25])

#sqrt : square root of the elements
print(sqrt(m4))

#std : calculates the standard deviation of given data along a specified axis.
print("Standard deviation : ",std(m4))

[2. 3. 5.]
Standard deviation :  8.9566858950296


In [22]:
#arange : starting to 0 to 20 range with 2 gap
print(arange(0,20,2))
print(arange(1,20,5))

#in float value
print(arange(0,20,2,float))

#same as arange but default in float
print(linspace(0,20,5))

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  6 11 16]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
[ 0.  5. 10. 15. 20.]


In [25]:
#the row and column indices of each element are swapped.
ht = h.T
print(ht)

[[1 3]
 [2 4]
 [5 7]
 [6 8]]


In [26]:
#nditer : This creates an iterator object that will iterate over the elements of the array ht
for i in nditer(ht):
    print("element : ",i)

element :  1
element :  2
element :  5
element :  6
element :  3
element :  4
element :  7
element :  8


In [28]:
#hsplit : return the array in the horizontal form
m1 = array([[1,2],[3,4]])
m2 = array([[5,6],[7,8]])
h = hstack((m1,m2))
hnew = hsplit(h,2)
print(hnew)

#vsplit : return the array in the vertical form
v = vstack((m1,m2))
vnew = vsplit(v,2)
print(vnew)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [30]:
arr = array([23,34,45,67])

#sqrt : Returns the square root of each element
print("Sqrt : ",sqrt(arr))

#exp : Returns the exponentials of each element
print("Exp: ",exp(arr))

#sin : Returns the sin of each element
print("Sin: ",sin(arr))

#cos : Returns the cosine of each element
print("Cos:",cos(arr))

#log : Returns the logarithm of each element
print("Log: ",log(arr))

#sum : Returns the sum total of elements in the array
print("Sum: ",sum(arr))

#std : Returns the standard deviation of in the array
print("Std: ",std(arr))

Sqrt :  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos: [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945
